# Generated by Django 3.2.5 on 2021-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_custaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custaddress',
            name='log',
        ),
        migrations.AddField(
            model_name='custaddress',
            name='lon',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custaddress',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
    ]
