# Generated by Django 4.0 on 2021-12-23 08:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_disc', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('seller_cr', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('shopname', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='products/sellers/')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
    ]
