# Generated by Django 3.2.5 on 2021-07-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='gender',
        ),
    ]
