# Generated by Django 3.2.5 on 2021-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='lat',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='log',
            field=models.CharField(default=50, max_length=100),
            preserve_default=False,
        ),
    ]
